export WHEELIE_CONE_X_BASE=0.75
export WHEELIE_CONE_X_PER_AREA=0.7
export WHEELIE_CONE_MIN_HEIGHT=0.05
export WHEELIE_TRACKING_X_SPEED=0.18

export WHEELIE_TURN_BEGIN_AREA_THRESHOLD=0.25
export WHEELIE_TURN_X_SPEED=0.24
export WHEELIE_TURN_STEER_SPEED=0.05

export WHEELIE_LOST_X_SPEED=0.12
export WHEELIE_LOST_STEER_SPEED=0.04

export WHEELIE_PRETURN_TIME=0.17
export WHEELIE_PRETURN_X_SPEED=0
export WHEELIE_PRETURN_STEER_SPEED=-0.2

export WHEELIE_TRACKING_K_P=-0.12

